### ISSUE TITLE
HUD.exe

### ISSUE THREAD

**Issue by knopa** [liuziangexit/HEIF-Utility#1]
What is that?

**Comment by liuziangexit** [comment]
C# use commad line to call HUD.exe to do the actual conversion work.HUD's source code in here:https://github.com/liuziangexit/HEIF-Utility-CommandLineTool

**Comment by knopa** [comment]
I see. It's from Nokia. I have an issue only 512x512 resolution. Do you
know how to choose proper image from list?

**Comment by liuziangexit** [comment]
> Do you know how to choose proper image from list?

what list?

**Comment by knopa** [comment]
As you know heif could have more than image inside, and now it  took only
first one. But main image not converted

**Comment by liuziangexit** [comment]
OK i know what do you mean...

**Comment by liuziangexit** [comment]
well,this is very simple.
first, you clone this git https://github.com/liuziangexit/HEIF-Utility-CommandLineTool.
and then you open this file:HEIF-Utility-CommandLineTool/Srcs/HUD/main.cpp.

in line 66,you change the index of "ids"...and you can choose which pic in the list...
i mean,such as when you need first one,you write
`const uint32_t itemId = ids[0];`
when you need second one,you write
`const uint32_t itemId = ids[1];`
you need third one
`const uint32_t itemId = ids[2];`
and so on...

after you change the code, use CMake rebuild this.

i guess you can get what i mean, my english is not good...

**Comment by knopa** [comment]
You are correct. Thanks for information
