### ISSUE TITLE
Code is not Running in System 

### ISSUE THREAD

**Issue by prateek1108** [liuziangexit/HEIF-Utility#10]
Hello Sir,

I had tried to build this code on my machine with visual studio 2015 on windows 10 operating system. I got an error "The core component is missing. HEIF UTILITY cannot start".

**Comment by prateek1108** [comment]
hello Sir,
I think there is a problem in giving arguments to this code ....is it a single argument i.e file path of heic

**Comment by liuziangexit** [comment]
@prateek1108 Hello, this is not a bug, this is a feature.

HEIF Utility need some dynamic library file to convert image. If can not find those DLL files, it will pop up this dialog and exit.

` if (
!System.IO.File.Exists(Application.StartupPath + "\\HUD.dll") || !System.IO.File.Exists(Application.StartupPath + "\\opencv_ffmpeg330_64.dll") || !System.IO.File.Exists(Application.StartupPath + "\\opencv_world330.dll"))
                {
                    MessageBox.Show("The core component is missing, HEIF Utility can not start.");
                    Environment.Exit(0);
                }`

HEIF Utility need these 3 DLLs:
You can built HUD.dll from https://github.com/liuziangexit/HEIF-Utility-Native-DLL.
The opencv_ffmpeg330_64.dll and opencv_world330.dll is part of OpenCV, you can download OpenCV source code to built them.

Those DLLs should be placed in the same directory as the main program(HEIF-Utility.exe).

If you don't want to built them by yourself, you can just simply download a HEIF Utility binary package(https://liuziangexit.com/HEIF-Utility/download.html) , and copy them.

**Comment by prateek1108** [comment]
Hello Sir,
Thanks alot for replying on my query. I had followed the steps given by you 
and now i am able to debug the code.......The problem now i am facing to decrypt or decompress the image it showing a error "Unable to open this file" but by online decompresses its decompressing

**Comment by liuziangexit** [comment]
@prateek1108 can you send me that file?

**Comment by prateek1108** [comment]
Hello Sir,
Sorry for late reply....I am trying to do this by placing these dlls in debug and release folder......
Now it is working fine .....But on my another system With Windows 10 64bit System its showing same error my be its my system issue..... i am trying to check this issue ...Soon i will update you in both the cases.......
