### ISSUE TITLE
Error Unable to open this file

### ISSUE THREAD

**Issue by calLsOLoIsNOob** [liuziangexit/HEIF-Utility#14]
Hi I'm trying to convert a batch of HEIC's to JPG. I'm getting an error: "Unable to open this file". Tried other online converters. All giving me errors. Can you please help me figure out whats going on?

One of the photos: [IMG_1163.zip](https://github.com/liuziangexit/HEIF-Utility/files/1504393/IMG_1163.zip)

**Comment by calLsOLoIsNOob** [comment]
Update: Google photos managed to upload the HEIC's. And I saved them as JPG.

**Comment by liuziangexit** [comment]
Well...my program has 10% failure rate...
