### ISSUE TITLE
Using on an ASP.NET site > image invalid format

### ISSUE THREAD

**Issue by mjoehl** [liuziangexit/HEIF-Utility#19]
I used your libraries to convert HEIF to JPEG. And on a windows machine (Console-Application) it works like a charm.

Now I try to do the same thing on an ASP.NET site (Web-API) to convert incoming images.

I don't get an error message from the HUD.dll while converting the file. It seems like it works, because I successfully get a ByteArray as a result form the "invoke_heif2jpg" method.

But when I try to save this result-byte-array as a jpeg, the image is corrupted. The format is wrong.
I get a "System.ArgumentException: Invalid parameter" exception when I call the following code:

`var image = Image.FromStream(new MemoryStream(jpegByteArray));`

I have this problem when I call the HUD.dll directly form withing the API-Method and (like [your ONLINE-code](https://github.com/liuziangexit/HEIF-Utility-Online)) when I start a separate process.

What can be wrong? Thanks

**Comment by liuziangexit** [comment]
The Readme.md in HUD(https://github.com/liuziangexit/HEIF-Utility-Native-DLL/tree/master/EnglishIntro) is Outdated...I will update the documents right now, and when I finish, I will tell you(soon! should be done in 10 minutes!

**Comment by liuziangexit** [comment]
@mjoehl document has been update.
https://github.com/liuziangexit/HEIF-Utility-Native-DLL/tree/master/EnglishIntro

if it still not work, i can use TeamViewer to help you

**Comment by mjoehl** [comment]
Thanks for your realy fast answer. First I updated everything to the new sources (including the ICC profiels).

After that I found the problem within my ASP.NET project.
The third parameter "temp_filename" must be an absolute path to the file in the Web-Environment. Without an absolute path (just like in your winforms project) the program tries to write the temp-file to a path without access.

So I just added following code before calling the "invoke_heif2jpg" method:

```
var tmpFolder = Server.MapPath("~/tmp");
var tmpFile = Path.Combine(tmpFolder, "temp_bitstream.hevc");

if (!Directory.Exists(tmpFolder))
{
    Directory.CreateDirectory(tmpFolder);
}

var has_icc = HeifHelper.read_profile();

var copysize = 0;
var jpegBytes = HeifHelper.invoke_heif2jpg(fileBytes, 100, tmpFile, ref copysize, false, has_icc);
```
Wow... thats so silly afterwards...

**Comment by liuziangexit** [comment]
im not professional in C# and Web Develop, i build a command line program to invoke HUD.dll, and use C# to invoke the command line program...I know this is not perfect...

**Comment by liuziangexit** [comment]
anyway, if you can't invoke HUD.dll, just ask me.(or if you want to build HUD.dll from source code, I can help you)

**Comment by mjoehl** [comment]
Everything works now. The path was just the problem.
Thanks

**Comment by liuziangexit** [comment]
you are welcome
