### ISSUE TITLE
high dpi support

### ISSUE THREAD

**Issue by bitching** [liuziangexit/HEIF-Utility#23]
target project to .net framework 4.6 and add the following code to `app.config`:
```csharp
  <appSettings>
    <add key="EnableWindowsFormsHighDpiAutoResizing" value="true" />
  </appSettings>
```
and add a manifest file `app.manifest`, the settings should be generated automatically, enable the following section:
```csharp
  <application xmlns="urn:schemas-microsoft-com:asm.v3">
    <windowsSettings>
      <dpiAware xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">true</dpiAware>
    </windowsSettings>
  </application>
```
and rebuild.
the ui will support high dpi.

**Comment by bitching** [comment]
<img width="512" alt="ss" src="https://user-images.githubusercontent.com/12702029/40980270-8f048d90-690a-11e8-9f29-bbc6c14d7479.png">

**Comment by liuziangexit** [comment]
good evening.
thank you for your suggestion.
to support HiDPI, i am writing a WPF Remastered version, and its not finished yet.
If this is a more convenient way to provide HiDPI support, then i don't need to re-write a WPF version any more...
can you just make a pull request, and i will review it, if every thing is alright, i will merge it..

**Comment by liuziangexit** [comment]
merged
