### ISSUE TITLE
生成了HUD.dll后,C#如何调用

### ISSUE THREAD

**Issue by Dawnki** [liuziangexit/HEIF-Utility#25]
你好，我在win7 x64 上生成HUD解决方案，得到了HUD.dll后，怎么在c#的项目(比如console应用)中使用，我添加HUD.dll引用时提示不是有效的程序集或COM组件

**Comment by Dawnki** [comment]
https://github.com/liuziangexit/HEIF-Utility-Native-DLL ， emm，我应该在那个项目里提issue才对，不过这个issue我发出去之后关不了...

**Comment by liuziangexit** [comment]
@Dawnki

您好，首先请阅读 https://github.com/liuziangexit/HEIF-Utility-Native-DLL/blob/master/README.md 了解HUD.dll的函数接口

然后查看 https://github.com/liuziangexit/HEIF-Utility/blob/master/HEIF%20Utility/invoke_dll.cs 及对它的调用就可以很直观地了解如何在C#中使用HUD.dll的接口

如果您需要使用HUD.dll，这里有几点我需要声明一下。
1) HUD.dll解码HEIF文件时会需要写入磁盘中的临时文件，这是它的缺点之一，也是直接的性能瓶颈，这一点可以通过修改opencv源代码来优化
2) 这个项目使用的是2017年底的最新版nokiatech/heif，而那个版本无法解码极少数合法的HEIF文件，几率大概是千分之一，这是它的缺点之一。这可以通过使用新版本的nokiatech/heif代码重新编译HUD来修复（我猜）
3) 除此之外，没有任何已知的其他问题，并且HUD.dll已经在数以十万计的个人电脑上运作良好，所以我想可靠性大概是没问题的，但是依然不保证没有任何bug，如果有并且导致了事故，本人不负任何责任

如果有其他的疑问，请继续在这里留言
