### ISSUE TITLE
部分转换失败

### ISSUE THREAD

**Issue by iisure** [liuziangexit/HEIF-Utility#27]
非常好用，感谢。
但部分转换失败，貌似是因为这些图片在手机上被编辑过的原因（只用苹果自带图片编辑或snapspeed），能否研究一下。
再一个能否保存上一次批量转换的设置，输出路径和质量

**Comment by liuziangexit** [comment]
您好，部分图片不支持的问题是一直存在的，那是因为这个项目使用了较老版本的解码库。
此项目早在2018年初已经停止维护，所以很抱歉不能解决您提出的这些问题。
