### ISSUE TITLE
Unable to un-register HEIF-Utility-Thumbnail-Provider.dll with error code 0x80070002

### ISSUE THREAD

**Issue by weiqi-chen** [liuziangexit/HEIF-Utility#28]
I followed the instruction here https://liuziangexit.com/HEIF-Utility/Help/No14.html.

Here is the ouput:

![capture](https://user-images.githubusercontent.com/6562920/51364076-c54e0a80-1b15-11e9-9f62-83265d7cbe67.PNG)

```bash
$ sha1sum HEIF-Utility-Thumbnail-Provider.dll
3c03912eaf49dd76ed2f66d27ddd48d4a8344609  HEIF-Utility-Thumbnail-Provider.dll
```

![2](https://user-images.githubusercontent.com/6562920/51364163-2b3a9200-1b16-11e9-9e27-75fcb6de030b.PNG)

Anybody has any idea?

**Comment by liuziangexit** [comment]
@WeiqiChenCN 注册的时候应该没注册成功过吧？

**Comment by weiqi-chen** [comment]
我已经忘记了当年有没有注册成功过。我关掉issue吧，应该没关系了😂。
