### ISSUE TITLE
Unable to open file

### ISSUE THREAD

**Issue by deweydb** [liuziangexit/HEIF-Utility#3]
Hello,

I just downloaded your utility from your dropbox link, i am trying to use the english version on Windows 7.  When i open the file i get the error:
"Unable to open this file."
Please see example files here: https://wetransfer.com/downloads/85ba7bab2c08ccab582bc0c15812a77b20170918174707/9ac949e960baa80db1c5952fc53cfff820170918174707/2ef3df

**Comment by liuziangexit** [comment]
![image](https://user-images.githubusercontent.com/15322450/30583296-3db000e6-9d59-11e7-8360-916a1e4a2065.png)

i download one of HEIC file in you link,and use HEIF-Utility to open it and it just works.

**Comment by liuziangexit** [comment]
1.do not put HEIF-Utility in C:\Program Files or some other system folder like this.HEIF-Utility do not have write authority in system folder.
2.make sure your computer has installed Microsoft Visual C ++ 2015 Redistributable **x64**.
