### ISSUE TITLE
jpeg2heif

### ISSUE THREAD

**Issue by xyyjk** [liuziangexit/HEIF-Utility#4]
近期 Google 相册已经支持了 HEIF 格式的备份，此工具可以将 JPEG 图片转化为 HEIF 格式吗。为硬件、网盘同时节省空间。

**Comment by liuziangexit** [comment]
不行，这个是单向的，把 HEIF 转换为 JPEG，而不能反过来。

**Comment by xyyjk** [comment]
原因是目前没有开源库支持还是什么情况？
我找到一个网站不知道是否能有帮助 http://jpgtoheif.com/

**Comment by liuziangexit** [comment]
这个功能可以实现，没有技术上的障碍，但是我没有做，因为大部分的人只是想把 iPhone 的照片转成通用格式，而很少有人想要反过来。所以我只做了单向的。

**Comment by ghost** [comment]
@liuziangexit ,, 但是这样做更有意义呀

**Comment by liuziangexit** [comment]
@guoying1030 有其他人实现了这个功能，你可以尝试他们提供的解决方案

**Comment by ghost** [comment]
@liuziangexit ,http://jpgtoheif.com/ 这里提供的方案，太慢了。。。每秒钟才能使用ffmpeg处理一个。。。你有其他的方案吗？？？如果自己要实现，能否给个思路？

**Comment by liuziangexit** [comment]
@guoying1030 https://github.com/nokiatech/heif 用这个应该可以...吧，你看看官方文档 https://github.com/nokiatech/heif/wiki/II.-HEIF-Writer-Library-and-Configuration-Examples

**Comment by liuziangexit** [comment]
@guoying1030 首先你需要先把jpg转成hevc的，然后再用nokiatech/heif进行处理

**Comment by ghost** [comment]
@liuziangexit ,,jpg to hevc ,除了ffmpeg可以做，还有其他的吗？因为ffmpeg使用x265太慢了。。

**Comment by liuziangexit** [comment]
@guoying1030 我不是很清楚了
