### ISSUE TITLE
hi dpi support?

### ISSUE THREAD

**Issue by bitching** [liuziangexit/HEIF-Utility#8]
The UI blurs on my 150% dpi monitor.

**Comment by liuziangexit** [comment]
Thank you for your report.
I want to fix it, but i don't have a high dpi screen.
you can try to fix it by folo this:
http://crsouza.com/2015/04/13/how-to-fix-blurry-windows-forms-windows-in-high-dpi-settings/
after you fix it, you create a Pull requests, and after review i will merge it.
thx.

**Comment by liuziangexit** [comment]
Maybe I can fix it in a few days

**Comment by liuziangexit** [comment]
This can't be done...Unless someone use WPF rewrite the UI...

**Comment by liuziangexit** [comment]
processing...

**Comment by liuziangexit** [comment]
The new version with HiDPI support will be released in the next few days, thank you for your contribution.
