### ISSUE TITLE
Nokia 官網圖片不能顥示

### ISSUE THREAD

**Issue by itsnotvalid** [liuziangexit/HEIF-Utility#9]
測試用文件: https://github.com/nokiatech/heif/blob/gh-pages/content/images/cheers_1440x960.heic

拿到app去, 只顥示無法打開文件，並沒有進一步報錯。

謝謝

**Comment by liuziangexit** [comment]
你好，這是一個 feature，而不是 bug。
這個軟件只支持來自 iOS 的 HEIF 文件，而不支持普通的 HEIF 文件。
謝謝你的反饋。

**Comment by liuziangexit** [comment]
Apple HEIF 的示例文件在 https://github.com/liuziangexit/HEIF-Utility-Native-DLL/tree/master/Examples

**Comment by itsnotvalid** [comment]
這樣太可惜了, 不過原來heic下面可以放多個tile...這樣玩下去真的很麻煩...

**Comment by liuziangexit** [comment]
有关 Apple HEIF 的更多信息，请参阅 https://zhuanlan.zhihu.com/p/29439313 和 https://developer.apple.com/videos/play/wwdc2017/503/
